### ISSUE TITLE
Great Plugin

### ISSUE THREAD

**Issue by bkrajendra** [SaifurRahmanMohsin/oc-oauth2-plugin#1]
I was waiting for someone to start with oAuth2 using passport for octobercms.
Passport is best way to oAuth2.
Im using it on my many production instances using laravel.
making it working with OCMS is little tricky as its user auth is different than laravel's.

I hope you might have checked https://github.com/LukeTowers/oc-passport-plugin
If i get time I'll definitely try to contribute.

Thanks!

**Comment by mohsin** [comment]
Firstly, thanks a lot for the review. I’m glad that you like it.

I’ve already tried Luke’s plugin and it’s currently incomplete nor does not suit my need, which is why I made this plugin. Besides, Luke has planned it a particular way whereas I have planned that my plugin integrates with my RESTful plugin as well which would boost up the usage and would also [make my users happy](https://github.com/SaifurRahmanMohsin/RESTful-Plugin/issues/12) as it will solve REST API auth in a concise way. I had planned this plugin a long time ago but haven’t been able to work on it due to work contracts and was finally able to build this only now. Hopefully, this month I’ll get to finish the Auth plugin as well and make this plugin compatible with Auth and also link it up to RESTful so that OctoberCMS becomes a goto platform for building API-based backends that work with mobile apps.
