### ISSUE TITLE
Is this complete?

### ISSUE THREAD

**Issue by b8ne** [SaifurRahmanMohsin/oc-oauth2-plugin#2]
Hi is this plugin complete?

`OAuth2ServiceProvider.php` looks to have a lot of redundant code in it.
And `registerAuthMechanisms()` is never called?

**Comment by SaifurRahmanMohsin** [comment]
Yes, this plugins works fine if that’s what you’re asking. Is it complete?—No. I plan to add more features and make it simpler.

**Comment by mohsin** [comment]
@b8ne Yes, this plugins works fine if that’s what you’re asking. Is it complete?—No. I’ve planned to add more features and make it simpler.

registerAuthMechanisms is called by other plugins that need to register their own custom auth mechanisms. For example, there could be a plugin called AWSAuth that hooks into this and registers AWS Signature Auth. Or you can use my own OAuth 2 plugin that calls this method to enable OAuth 2 mechanism. The reason this plugin exists is so that it acts as an intermediary between custom auth mechanism and my RESTful plugin so that I can swap out Auth mechanisms depending on my necessity.
